msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2021-05-25 15:06+0000\n"
"Last-Translator: \n"
"Language-Team: Finnish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Project-ID: 289505\n"
"X-Crowdin-Language: fi\n"
"X-Crowdin-File-ID: 670\n"
"Language: fi_FI\n"

#: redbot/cogs/audio/core/events/cog.py:215
msgid "Auto Play started."
msgstr "Automaattinen toisto aloitettu."

#: redbot/cogs/audio/core/events/dpy.py:40
msgid "You have attempted to run Audio's Lavalink server on an unsupported architecture. Only settings related commands will be available."
msgstr "Yrität Audion Lavalink-palvelinta arkkitehtuurilla jota ei tueta. Vain asetuksiin liittyvät komennot ovat käytettävissä."

#: redbot/cogs/audio/core/events/dpy.py:70
msgid "I'm missing permissions in this server, Please address this as soon as possible.\n\n"
"Expected Permissions:\n"
msgstr "Minulta puuttuu oikeuksia tällä palvelimella, korjaathan tämän mahdollisimman pian.\n\n"
"Puuttuvat oikeudet:\n"

#: redbot/cogs/audio/core/events/dpy.py:77
msgid "Enabled"
msgstr "Käytössä"

#: redbot/cogs/audio/core/events/dpy.py:77
msgid "Disabled"
msgstr "Ei käytössä"

#: redbot/cogs/audio/core/events/dpy.py:124
msgid "No DJ role found. Disabling DJ mode."
msgstr "DJ-roolia ei löydy. Poistetaan DJ-tila käytöstä."

#: redbot/cogs/audio/core/events/dpy.py:134
msgid "`{user_input}` is not a valid value for `{command}`"
msgstr "`{user_input}` ei ole kelvollinen arvo kohteelle `{command}`"

#: redbot/cogs/audio/core/events/dpy.py:142
msgid "Unable To Parse Argument"
msgstr "Argumentin käsittely epäonnistui"

#: redbot/cogs/audio/core/events/dpy.py:154
#: redbot/cogs/audio/core/events/dpy.py:163
msgid "Invalid Argument"
msgstr "Virheellinen argumentti"

#: redbot/cogs/audio/core/events/dpy.py:155
msgid "The argument you gave for `{}` is not valid: I was expecting a `{}`."
msgstr "Argumentti jonka annoit kohteelle `{}` ei ole kelvollinen: Oletin että saan`{}`."

#: redbot/cogs/audio/core/events/dpy.py:175
msgid "Invalid Environment"
msgstr "Virheellinen ympäristö"

#: redbot/cogs/audio/core/events/dpy.py:176
msgid "Connection to Lavalink has been lost."
msgstr "Yhteys Lavalinkkiin menetettiin."

#: redbot/cogs/audio/core/events/dpy.py:184
msgid "No Player Available"
msgstr "Toistinta ei saatavilla"

#: redbot/cogs/audio/core/events/dpy.py:185
msgid "The bot is not connected to a voice channel."
msgstr "Botti ei ole yhdistettynä puhekanavaan."

#: redbot/cogs/audio/core/events/dpy.py:193
#: redbot/cogs/audio/core/events/lavalink.py:162
msgid "Unable to Get Track"
msgstr "Kappaletta ei voitu hakea"

#: redbot/cogs/audio/core/events/dpy.py:194
#: redbot/cogs/audio/core/events/lavalink.py:163
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr "En saa kappaletta Lavalinkiltä tällä hetkellä, yritä uudelleen muutaman minuutin kuluttua."

#: redbot/cogs/audio/core/events/dpy.py:205
msgid "There was an issue communicating with Discord."
msgstr "Ongelma Discordin kanssa kommunikoitaessa."

#: redbot/cogs/audio/core/events/dpy.py:206
msgid "This error has been reported to the bot owner."
msgstr "Tämä virhe ilmoitettiin botin omistajalle."

#: redbot/cogs/audio/core/events/lavalink.py:154
msgid "Couldn't get a valid track."
msgstr "Kelvollista kappaletta ei saatu."

#: redbot/cogs/audio/core/events/lavalink.py:189
msgid "Now Playing"
msgstr "Nyt toistetaan"

#: redbot/cogs/audio/core/events/lavalink.py:191
msgid "Track length: {length} | Requested by: {user}"
msgstr "Kappaleen pituus: {length} | Pyytäjä: {user}"

#: redbot/cogs/audio/core/events/lavalink.py:212
msgid "Queue ended."
msgstr "Jono päättyi."

#: redbot/cogs/audio/core/events/lavalink.py:264
msgid "Multiple Errors Detected"
msgstr "Useita virheitä havaittu"

#: redbot/cogs/audio/core/events/lavalink.py:265
msgid "Closing the audio player due to multiple errors being detected. If this persists, please inform the bot owner as the Audio cog may be temporally unavailable."
msgstr "Monia virheitä havaittiin ja sen vuoksi äänentoisto suljettiin. Jos tämä ongelma jatkuu, ota yhteyttä botin omistajaan, sillä Audio-lisäosa voi olla hetkellisesti poissa käytöstä."

#: redbot/cogs/audio/core/events/lavalink.py:279
msgid "Track Stuck"
msgstr "Kappale jumissa"

#: redbot/cogs/audio/core/events/lavalink.py:280
msgid "Playback of the song has stopped due to an unexpected error.\n"
"{error}"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:286
msgid "Track Error"
msgstr "Kappalevirhe"

